# Generated by Django 5.1.3 on 2024-11-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='media_type',
            field=models.CharField(choices=[('image', '图片'), ('video', '视频')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='pic',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
