# Generated by Django 3.2.11 on 2024-09-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='collect',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
