# Generated by Django 3.2.11 on 2024-11-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_note_collect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.PositiveIntegerField()),
                ('pic', models.ImageField(upload_to='pic/')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
        migrations.RemoveField(
            model_name='note',
            name='collect',
        ),
        migrations.RemoveField(
            model_name='note',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='note',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
        migrations.RemoveField(
            model_name='note',
            name='text',
        ),
        migrations.AddField(
            model_name='note',
            name='pic',
            field=models.ManyToManyField(blank=True, null=True, related_name='pic_note', to='notes.Pic'),
        ),
        migrations.AddField(
            model_name='note',
            name='text',
            field=models.ManyToManyField(blank=True, null=True, related_name='text_note', to='notes.Text'),
        ),
    ]
