# Generated by Django 3.2.11 on 2024-11-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20241101_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='pic',
            field=models.ManyToManyField(blank=True, related_name='pic_note', to='notes.Pic'),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.ManyToManyField(blank=True, related_name='text_note', to='notes.Text'),
        ),
    ]
