# Generated by Django 3.2.11 on 2024-11-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20241101_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='temp',
            field=models.CharField(default='Mult', max_length=10),
        ),
    ]
