# Generated by Django 3.2.11 on 2024-11-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_accesslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
