# Generated by Django 4.2.5 on 2023-10-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_reset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('vc_code', models.CharField(max_length=64)),
                ('send_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
