# Generated by Django 3.2.11 on 2024-10-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(null=True, upload_to='avatar/'),
        ),
    ]
