# Generated by Django 3.2.11 on 2024-10-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20241028_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='data',
            new_name='jsondata',
        ),
    ]
